---
- name: Apache | Create directory sites-available
  file: 
    path: /etc/httpd/sites-available 
    state: directory
    owner: apache
    group: apache

- name: Apache | Create directory sites-enabled
  file:
    path: /etc/httpd/sites-enabled
    state: directory
    owner: apache
    group: apache

- name: WordPress | Apache | Copy virtual host configuration file
  template: src=apache-vhost.conf.j2 dest=/etc/httpd/sites-available/{{wp_apache_hostname}}.conf owner=root group=root mode=0644

- name: WordPress | Apache | Symlink virtual host configuration file from sites-available to sites-enabled
  file: state=link src=/etc/httpd/sites-available/{{wp_apache_hostname}}.conf
        dest=/etc/httpd/sites-enabled/{{wp_apache_hostname}}.conf owner=root group=root mode=0644
